// Mock-Daten für Test-Fahndungen
// Provisorische Fahndungskarten mit Platzhalterbildern bis zur Integration mit Typo3 Headless
import type { FahndungItem } from "./typo3Client";

export const mockFahndungen: FahndungItem[] = [
  {
    id: 1,
    title: "Vermisste Person: Daniel Hartwick",
    description:
      "Seit dem 15. Januar 2024 wird Daniel Hartwick vermisst. Er wurde zuletzt in der Innenstadt von Stuttgart gesehen. Daniel ist 1,75m groß, hat braune Haare und braune Augen. Er trug zum Zeitpunkt des Verschwindens eine blaue Jeans und ein rotes T-Shirt.",
    summary:
      "Vermisste Person seit 15. Januar 2024. Zuletzt in Stuttgart gesehen.",
    status: "active",
    type: "missing_person",
    location: "Stuttgart",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-16T10:00:00Z",
    slug: "vermisste-person-daniel-hartwick",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Daniel Hartwick.webp",
      alternative: "Foto von Daniel Hartwick",
    },
    isNew: true,
    date: "2024-01-15",
    kategorie: "VERMISSTE",
    tatzeit: "15.01.2024, ca. 14:00 Uhr",
    dienststelle: "Polizeipräsidium Stuttgart",
  },
  {
    id: 2,
    title: "Gesuchter Straftäter: Freya Lindholm",
    description:
      "Am 20. Januar 2024 wurde ein Juweliergeschäft in der Königstraße in Stuttgart aufgebrochen. Die Täterin entwendete Schmuck im Wert von über 50.000 Euro. Zeugen beschrieben eine weibliche Täterin, ca. 1,70m groß, schlank, mit Kapuze. Die Polizei bittet um Hinweise.",
    summary:
      "Einbruch in Juweliergeschäft in Stuttgart. Schmuck im Wert von über 50.000 Euro entwendet.",
    status: "active",
    type: "wanted",
    location: "Stuttgart, Königstraße",
    delikt: "Schwerer Diebstahl",
    publishedAt: "2024-01-21T08:00:00Z",
    slug: "gesuchter-straftaeter-freya-lindholm",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Freya Lindholm.webp",
      alternative: "Gesuchte Straftäterin: Freya Lindholm",
    },
    isNew: true,
    date: "2024-01-20",
    kategorie: "STRAFTÄTER",
    tatzeit: "20.01.2024, zwischen 22:00 und 23:30 Uhr",
    dienststelle: "Polizeipräsidium Stuttgart",
  },
  {
    id: 3,
    title: "Vermisste Person: Hana Mitsuki",
    description:
      "Hana Mitsuki wird seit dem 12. Januar 2024 vermisst. Sie wurde zuletzt in Karlsruhe gesehen. Hana ist 1,65m groß, hat schwarze Haare und braune Augen. Sie trug eine schwarze Lederjacke und eine blaue Jeans. Die Familie ist sehr besorgt.",
    summary:
      "Vermisste Person seit 12. Januar 2024. Zuletzt in Karlsruhe gesehen.",
    status: "active",
    type: "missing_person",
    location: "Karlsruhe",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-13T09:00:00Z",
    slug: "vermisste-person-hana-mitsuki",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Hana Mitsuki.webp",
      alternative: "Foto von Hana Mitsuki",
    },
    isNew: false,
    date: "2024-01-12",
    kategorie: "VERMISSTE",
    tatzeit: "12.01.2024, ca. 18:00 Uhr",
    dienststelle: "Polizeipräsidium Karlsruhe",
  },
  {
    id: 4,
    title: "Gesuchter Straftäter: Henrik Solberg",
    description:
      "In der Nacht zum 22. Januar 2024 wurde eine Tankstelle in Mannheim überfallen. Der Täter bedrohte den Angestellten mit einer Waffe und erbeutete Bargeld. Der Täter wird als männlich, ca. 1,85m groß, kräftige Statur beschrieben. Er trug eine schwarze Kapuze und eine dunkle Jacke.",
    summary:
      "Raubüberfall auf Tankstelle in Mannheim. Täter mit Waffe bedroht Angestellten.",
    status: "active",
    type: "wanted",
    location: "Mannheim",
    delikt: "Raub",
    publishedAt: "2024-01-22T06:00:00Z",
    slug: "gesuchter-straftaeter-henrik-solberg",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Henrik Solberg.webp",
      alternative: "Gesuchter Straftäter: Henrik Solberg",
    },
    isNew: true,
    date: "2024-01-22",
    kategorie: "STRAFTÄTER",
    tatzeit: "22.01.2024, zwischen 02:00 und 02:30 Uhr",
    dienststelle: "Polizeipräsidium Mannheim",
  },
  {
    id: 5,
    title: "Vermisste Person: Julian Reyes",
    description:
      "Julian Reyes wird seit dem 10. Januar 2024 vermisst. Er wurde zuletzt in Freiburg gesehen. Julian ist 1,82m groß, hat schwarze Haare und braune Augen. Er trug eine graue Jacke und schwarze Hosen. Die Polizei bittet um Hinweise zu seinem Verbleib.",
    summary:
      "Vermisste Person seit 10. Januar 2024. Zuletzt in Freiburg gesehen.",
    status: "active",
    type: "missing_person",
    location: "Freiburg",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-11T14:00:00Z",
    slug: "vermisste-person-julian-reyes",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Julian Reyes.webp",
      alternative: "Foto von Julian Reyes",
    },
    isNew: false,
    date: "2024-01-10",
    kategorie: "VERMISSTE",
    tatzeit: "10.01.2024, ca. 15:00 Uhr",
    dienststelle: "Polizeipräsidium Freiburg",
  },
  {
    id: 6,
    title: "Gesuchter Straftäter: Liora Kessler",
    description:
      "In der Nacht zum 19. Januar 2024 wurden in Heilbronn mehrere parkende Fahrzeuge beschädigt. Die Täterin zerkratzte die Lacke und zerstörte Außenspiegel. Zeugen sahen eine weibliche Person, die sich verdächtig verhielt. Die Polizei sucht nach Hinweisen.",
    summary:
      "Sachbeschädigung an mehreren Fahrzeugen in Heilbronn. Gesuchte Täterin.",
    status: "active",
    type: "wanted",
    location: "Heilbronn",
    delikt: "Sachbeschädigung",
    publishedAt: "2024-01-20T10:00:00Z",
    slug: "gesuchter-straftaeter-liora-kessler",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Liora Kessler.webp",
      alternative: "Gesuchte Straftäterin: Liora Kessler",
    },
    isNew: false,
    date: "2024-01-19",
    kategorie: "STRAFTÄTER",
    tatzeit: "19.01.2024, zwischen 23:00 und 01:00 Uhr",
    dienststelle: "Polizeipräsidium Heilbronn",
  },
  {
    id: 7,
    title: "Vermisste Person: Markus Varela",
    description:
      "Markus Varela wird seit dem 17. Januar 2024 vermisst. Er wurde zuletzt in Tübingen gesehen. Markus ist 1,78m groß, hat braune Haare und blaue Augen. Er trug eine rote Jacke und eine schwarze Hose. Die Familie ist sehr besorgt und bittet um Hinweise.",
    summary:
      "Vermisste Person seit 17. Januar 2024. Zuletzt in Tübingen gesehen.",
    status: "active",
    type: "missing_person",
    location: "Tübingen",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-18T11:00:00Z",
    slug: "vermisste-person-markus-varela",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Markus Varela.webp",
      alternative: "Foto von Markus Varela",
    },
    isNew: false,
    date: "2024-01-17",
    kategorie: "VERMISSTE",
    tatzeit: "17.01.2024, ca. 19:00 Uhr",
    dienststelle: "Polizeipräsidium Tübingen",
  },
  {
    id: 8,
    title: "Gesuchter Straftäter: Mateo Ordoñez",
    description:
      "Am 18. Januar 2024 ereignete sich ein Raubüberfall auf der B27 bei Ludwigsburg. Der Täter entwendete Wertsachen und flüchtete anschließend. Die Polizei sucht Zeugen, die den Vorfall beobachtet haben oder Informationen über den Täter haben.",
    summary: "Raubüberfall auf der B27 bei Ludwigsburg. Gesuchter Täter.",
    status: "active",
    type: "wanted",
    location: "Ludwigsburg, B27",
    delikt: "Raub",
    publishedAt: "2024-01-19T12:00:00Z",
    slug: "gesuchter-straftaeter-mateo-ordonez",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Mateo Ordoñez.webp",
      alternative: "Gesuchter Straftäter: Mateo Ordoñez",
    },
    isNew: false,
    date: "2024-01-18",
    kategorie: "STRAFTÄTER",
    tatzeit: "18.01.2024, ca. 16:30 Uhr",
    dienststelle: "Polizeipräsidium Ludwigsburg",
  },
  {
    id: 9,
    title: "Vermisste Person: Mei Lin Zhou",
    description:
      "Mei Lin Zhou wird seit dem 14. Januar 2024 vermisst. Sie wurde zuletzt in Heidelberg gesehen. Mei Lin ist 1,68m groß, hat schwarze Haare und braune Augen. Sie trug eine weiße Jacke und eine schwarze Hose. Die Familie ist sehr besorgt.",
    summary:
      "Vermisste Person seit 14. Januar 2024. Zuletzt in Heidelberg gesehen.",
    status: "active",
    type: "missing_person",
    location: "Heidelberg",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-15T08:00:00Z",
    slug: "vermisste-person-mei-lin-zhou",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Mei Lin Zhou.webp",
      alternative: "Foto von Mei Lin Zhou",
    },
    isNew: true,
    date: "2024-01-14",
    kategorie: "VERMISSTE",
    tatzeit: "14.01.2024, ca. 20:00 Uhr",
    dienststelle: "Polizeipräsidium Heidelberg",
  },
  {
    id: 10,
    title: "Zeugenaufruf: Rina Volkova",
    description:
      "In der Nacht zum 21. Januar 2024 kam es in einer Diskothek in Ulm zu einer Körperverletzung. Ein Gast wurde von mehreren unbekannten Personen angegriffen und verletzt. Die Polizei sucht Zeugen, die den Vorfall beobachtet haben oder Informationen über die Täter haben.",
    summary: "Körperverletzung in Diskothek in Ulm. Zeugen gesucht.",
    status: "active",
    type: "witness_appeal",
    location: "Ulm",
    delikt: "Körperverletzung",
    publishedAt: "2024-01-22T07:00:00Z",
    slug: "zeugenaufruf-rina-volkova",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Rina Volkova.webp",
      alternative: "Zeugenaufruf: Rina Volkova",
    },
    isNew: true,
    date: "2024-01-21",
    kategorie: "ZEUGENAUFRUF",
    tatzeit: "21.01.2024, zwischen 01:00 und 02:00 Uhr",
    dienststelle: "Polizeipräsidium Ulm",
  },
  {
    id: 11,
    title: "Vermisste Person: Talia Brooks",
    description:
      "Talia Brooks wird seit dem 16. Januar 2024 vermisst. Sie wurde zuletzt in Konstanz gesehen. Talia ist 1,72m groß, hat blonde Haare und grüne Augen. Sie trug eine gelbe Jacke und eine weiße Hose. Die Familie ist sehr besorgt und bittet um Hinweise.",
    summary:
      "Vermisste Person seit 16. Januar 2024. Zuletzt in Konstanz gesehen.",
    status: "active",
    type: "missing_person",
    location: "Konstanz",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-17T13:00:00Z",
    slug: "vermisste-person-talia-brooks",
    image: {
      url: "/images/placeholders/fotos/fahndungen/Talia Brooks.webp",
      alternative: "Foto von Talia Brooks",
    },
    isNew: true,
    date: "2024-01-16",
    kategorie: "VERMISSTE",
    tatzeit: "16.01.2024, ca. 17:00 Uhr",
    dienststelle: "Polizeipräsidium Konstanz",
  },
];
