// Mock-Daten für Test-Fahndungen
import type { FahndungItem } from "./typo3Client";

export const mockFahndungen: FahndungItem[] = [
  {
    id: 1,
    title: "Vermisste Person: Max Mustermann",
    description:
      "Seit dem 15. Januar 2024 wird Max Mustermann vermisst. Er wurde zuletzt in der Innenstadt von Stuttgart gesehen. Max ist 1,75m groß, hat braune Haare und braune Augen. Er trug zum Zeitpunkt des Verschwindens eine blaue Jeans und ein rotes T-Shirt.",
    summary:
      "Vermisste Person seit 15. Januar 2024. Zuletzt in Stuttgart gesehen.",
    status: "active",
    type: "missing_person",
    location: "Stuttgart",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-16T10:00:00Z",
    slug: "vermisste-person-max-mustermann",
    image: {
      url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
      alternative: "Foto von Max Mustermann",
    },
    isNew: true,
    date: "2024-01-15",
    kategorie: "VERMISSTE",
    tatzeit: "15.01.2024, ca. 14:00 Uhr",
    dienststelle: "Polizeipräsidium Stuttgart",
  },
  {
    id: 2,
    title: "Gesuchter Straftäter: Einbruch in Juweliergeschäft",
    description:
      "Am 20. Januar 2024 wurde ein Juweliergeschäft in der Königstraße in Stuttgart aufgebrochen. Der Täter entwendete Schmuck im Wert von über 50.000 Euro. Zeugen beschrieben einen männlichen Täter, ca. 1,80m groß, schlank, mit Kapuze. Die Polizei bittet um Hinweise.",
    summary:
      "Einbruch in Juweliergeschäft in Stuttgart. Schmuck im Wert von über 50.000 Euro entwendet.",
    status: "active",
    type: "wanted",
    location: "Stuttgart, Königstraße",
    delikt: "Schwerer Diebstahl",
    publishedAt: "2024-01-21T08:00:00Z",
    slug: "gesuchter-straftaeter-einbruch-juwelier",
    image: {
      url: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=600&fit=crop",
      alternative: "Gesuchter Straftäter",
    },
    isNew: true,
    date: "2024-01-20",
    kategorie: "STRAFTÄTER",
    tatzeit: "20.01.2024, zwischen 22:00 und 23:30 Uhr",
    dienststelle: "Polizeipräsidium Stuttgart",
  },
  {
    id: 3,
    title: "Zeugenaufruf: Verkehrsunfall mit Fahrerflucht",
    description:
      "Am 18. Januar 2024 ereignete sich ein Verkehrsunfall auf der B27 bei Ludwigsburg. Ein Fahrzeug verursachte einen Unfall und flüchtete anschließend. Die Polizei sucht Zeugen, die den Unfall beobachtet haben oder Informationen über das flüchtige Fahrzeug haben.",
    summary:
      "Verkehrsunfall mit Fahrerflucht auf der B27 bei Ludwigsburg. Zeugen gesucht.",
    status: "active",
    type: "witness_appeal",
    location: "Ludwigsburg, B27",
    delikt: "Fahrerflucht",
    publishedAt: "2024-01-19T12:00:00Z",
    slug: "zeugenaufruf-verkehrsunfall-fahrerflucht",
    image: {
      url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=600&fit=crop",
      alternative: "Unfallstelle",
    },
    isNew: false,
    date: "2024-01-18",
    kategorie: "ZEUGENAUFRUF",
    tatzeit: "18.01.2024, ca. 16:30 Uhr",
    dienststelle: "Polizeipräsidium Ludwigsburg",
  },
  {
    id: 4,
    title: "Vermisste Person: Anna Schmidt",
    description:
      "Anna Schmidt wird seit dem 12. Januar 2024 vermisst. Sie wurde zuletzt in Karlsruhe gesehen. Anna ist 1,65m groß, hat blonde Haare und grüne Augen. Sie trug eine schwarze Lederjacke und eine blaue Jeans. Die Familie ist sehr besorgt.",
    summary:
      "Vermisste Person seit 12. Januar 2024. Zuletzt in Karlsruhe gesehen.",
    status: "active",
    type: "missing_person",
    location: "Karlsruhe",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-13T09:00:00Z",
    slug: "vermisste-person-anna-schmidt",
    image: {
      url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=600&fit=crop",
      alternative: "Foto von Anna Schmidt",
    },
    isNew: false,
    date: "2024-01-12",
    kategorie: "VERMISSTE",
    tatzeit: "12.01.2024, ca. 18:00 Uhr",
    dienststelle: "Polizeipräsidium Karlsruhe",
  },
  {
    id: 5,
    title: "Gesuchter Straftäter: Raubüberfall auf Tankstelle",
    description:
      "In der Nacht zum 22. Januar 2024 wurde eine Tankstelle in Mannheim überfallen. Der Täter bedrohte den Angestellten mit einer Waffe und erbeutete Bargeld. Der Täter wird als männlich, ca. 1,75m groß, kräftige Statur beschrieben. Er trug eine schwarze Kapuze und eine dunkle Jacke.",
    summary:
      "Raubüberfall auf Tankstelle in Mannheim. Täter mit Waffe bedroht Angestellten.",
    status: "active",
    type: "wanted",
    location: "Mannheim",
    delikt: "Raub",
    publishedAt: "2024-01-22T06:00:00Z",
    slug: "gesuchter-straftaeter-raubueberfall-tankstelle",
    image: {
      url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=600&fit=crop",
      alternative: "Gesuchter Straftäter",
    },
    isNew: true,
    date: "2024-01-22",
    kategorie: "STRAFTÄTER",
    tatzeit: "22.01.2024, zwischen 02:00 und 02:30 Uhr",
    dienststelle: "Polizeipräsidium Mannheim",
  },
  {
    id: 6,
    title: "Vermisste Person: Peter Weber",
    description:
      "Peter Weber wird seit dem 10. Januar 2024 vermisst. Er wurde zuletzt in Freiburg gesehen. Peter ist 1,82m groß, hat schwarze Haare und braune Augen. Er trug eine graue Jacke und schwarze Hosen. Die Polizei bittet um Hinweise zu seinem Verbleib.",
    summary:
      "Vermisste Person seit 10. Januar 2024. Zuletzt in Freiburg gesehen.",
    status: "active",
    type: "missing_person",
    location: "Freiburg",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-11T14:00:00Z",
    slug: "vermisste-person-peter-weber",
    image: {
      url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop",
      alternative: "Foto von Peter Weber",
    },
    isNew: false,
    date: "2024-01-10",
    kategorie: "VERMISSTE",
    tatzeit: "10.01.2024, ca. 15:00 Uhr",
    dienststelle: "Polizeipräsidium Freiburg",
  },
  {
    id: 7,
    title: "Gesuchter Straftäter: Sachbeschädigung an mehreren Fahrzeugen",
    description:
      "In der Nacht zum 19. Januar 2024 wurden in Heilbronn mehrere parkende Fahrzeuge beschädigt. Die Täter zerkratzten die Lacke und zerstörten Außenspiegel. Zeugen sahen zwei männliche Personen, die sich verdächtig verhielten. Die Polizei sucht nach Hinweisen.",
    summary:
      "Sachbeschädigung an mehreren Fahrzeugen in Heilbronn. Zwei männliche Täter gesucht.",
    status: "active",
    type: "wanted",
    location: "Heilbronn",
    delikt: "Sachbeschädigung",
    publishedAt: "2024-01-20T10:00:00Z",
    slug: "gesuchter-straftaeter-sachbeschaedigung-fahrzeuge",
    image: {
      url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop",
      alternative: "Gesuchter Straftäter",
    },
    isNew: false,
    date: "2024-01-19",
    kategorie: "STRAFTÄTER",
    tatzeit: "19.01.2024, zwischen 23:00 und 01:00 Uhr",
    dienststelle: "Polizeipräsidium Heilbronn",
  },
  {
    id: 8,
    title: "Zeugenaufruf: Körperverletzung in Diskothek",
    description:
      "In der Nacht zum 21. Januar 2024 kam es in einer Diskothek in Ulm zu einer Körperverletzung. Ein Gast wurde von mehreren unbekannten Personen angegriffen und verletzt. Die Polizei sucht Zeugen, die den Vorfall beobachtet haben oder Informationen über die Täter haben.",
    summary: "Körperverletzung in Diskothek in Ulm. Zeugen gesucht.",
    status: "active",
    type: "witness_appeal",
    location: "Ulm",
    delikt: "Körperverletzung",
    publishedAt: "2024-01-22T07:00:00Z",
    slug: "zeugenaufruf-koerperverletzung-diskothek",
    image: {
      url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=600&fit=crop",
      alternative: "Zeugenaufruf",
    },
    isNew: true,
    date: "2024-01-21",
    kategorie: "ZEUGENAUFRUF",
    tatzeit: "21.01.2024, zwischen 01:00 und 02:00 Uhr",
    dienststelle: "Polizeipräsidium Ulm",
  },
  {
    id: 9,
    title: "Vermisste Person: Lisa Müller",
    description:
      "Lisa Müller wird seit dem 17. Januar 2024 vermisst. Sie wurde zuletzt in Tübingen gesehen. Lisa ist 1,70m groß, hat braune Haare und blaue Augen. Sie trug eine rote Jacke und eine schwarze Hose. Die Familie ist sehr besorgt und bittet um Hinweise.",
    summary:
      "Vermisste Person seit 17. Januar 2024. Zuletzt in Tübingen gesehen.",
    status: "active",
    type: "missing_person",
    location: "Tübingen",
    delikt: "Vermisste Person",
    publishedAt: "2024-01-18T11:00:00Z",
    slug: "vermisste-person-lisa-mueller",
    image: {
      url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop",
      alternative: "Foto von Lisa Müller",
    },
    isNew: false,
    date: "2024-01-17",
    kategorie: "VERMISSTE",
    tatzeit: "17.01.2024, ca. 19:00 Uhr",
    dienststelle: "Polizeipräsidium Tübingen",
  },
];
